version: "3.9"
services:
  web:
    build:
      context: .              # root
      dockerfile: Dockerfile  # root Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
